[package]
name = "docopt"
version = "0.6.54"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Command line argument parsing."
documentation = "http://burntsushi.net/rustdoc/docopt/"
homepage = "https://github.com/docopt/docopt.rs"
repository = "https://github.com/docopt/docopt.rs"
readme = "README.md"
keywords = ["docopt", "argument", "command", "argv"]
license = "Unlicense"

[lib]
name = "docopt"

[[bin]]
#name = "docopt-wordlist"
# Temporary, see https://github.com/rust-lang/cargo/issues/1450
name = "docopt_wordlist"
path = "src/wordlist.rs"
doc = false
test = false

[dependencies]
libc = "*"
regex = "*"
rustc-serialize = "0.3"
