[package]
name = "docopt_macros"
version = "0.6.5"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[lib]
name = "docopt_macros"
path = "src/macro.rs"
plugin = true

[dependencies.docopt]
path = ".."
